# Generated by Django 4.2.11 on 2024-03-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_linkcategory_id_alter_membershipapplication_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
